# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hangman_layout.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(240, 480)
        MainWindow.setMinimumSize(QtCore.QSize(240, 480))
        MainWindow.setMaximumSize(QtCore.QSize(240, 480))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica Neue"))
        font.setKerning(True)
        MainWindow.setFont(font)
        MainWindow.setWindowTitle(_fromUtf8("Hangman"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("resources/hangman.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setAnimated(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 220, 201))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.lbl_hangman_drawing = QtGui.QLabel(self.groupBox)
        self.lbl_hangman_drawing.setGeometry(QtCore.QRect(10, 30, 201, 161))
        self.lbl_hangman_drawing.setText(_fromUtf8(""))
        self.lbl_hangman_drawing.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_hangman_drawing.setObjectName(_fromUtf8("lbl_hangman_drawing"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 280, 220, 55))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.lbl_missed_letters = QtGui.QLabel(self.groupBox_2)
        self.lbl_missed_letters.setGeometry(QtCore.QRect(10, 20, 200, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica Neue"))
        self.lbl_missed_letters.setFont(font)
        self.lbl_missed_letters.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_missed_letters.setObjectName(_fromUtf8("lbl_missed_letters"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 340, 220, 66))
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.btn_guess = QtGui.QPushButton(self.groupBox_3)
        self.btn_guess.setGeometry(QtCore.QRect(140, 30, 80, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica Neue"))
        self.btn_guess.setFont(font)
        self.btn_guess.setCheckable(False)
        self.btn_guess.setObjectName(_fromUtf8("btn_guess"))
        self.lineEdit_guess = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_guess.setGeometry(QtCore.QRect(10, 34, 127, 21))
        self.lineEdit_guess.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_guess.setObjectName(_fromUtf8("lineEdit_guess"))
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 200, 220, 80))
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.lbl_masked_word = QtGui.QLabel(self.groupBox_4)
        self.lbl_masked_word.setGeometry(QtCore.QRect(5, 22, 211, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica Neue"))
        font.setPointSize(16)
        self.lbl_masked_word.setFont(font)
        self.lbl_masked_word.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_masked_word.setObjectName(_fromUtf8("lbl_masked_word"))
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 410, 220, 40))
        self.groupBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.lbl_guesses_remaining = QtGui.QLabel(self.groupBox_5)
        self.lbl_guesses_remaining.setGeometry(QtCore.QRect(10, 15, 200, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_guesses_remaining.setFont(font)
        self.lbl_guesses_remaining.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_guesses_remaining.setObjectName(_fromUtf8("lbl_guesses_remaining"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 240, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        MainWindow.setMenuBar(self.menubar)
        self.actionLoad_custom_word_list = QtGui.QAction(MainWindow)
        self.actionLoad_custom_word_list.setObjectName(_fromUtf8("actionLoad_custom_word_list"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionView_Previous_Scores = QtGui.QAction(MainWindow)
        self.actionView_Previous_Scores.setObjectName(_fromUtf8("actionView_Previous_Scores"))
        self.actionClear_previous_scores = QtGui.QAction(MainWindow)
        self.actionClear_previous_scores.setObjectName(_fromUtf8("actionClear_previous_scores"))
        self.menuFile.addAction(self.actionLoad_custom_word_list)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuView.addAction(self.actionView_Previous_Scores)
        self.menuEdit.addAction(self.actionClear_previous_scores)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.groupBox.setTitle(_translate("MainWindow", "Will he hang?", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Missed Letters", None))
        self.lbl_missed_letters.setText(_translate("MainWindow", "Missed Letters", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Enter a letter or the whole word here", None))
        self.btn_guess.setText(_translate("MainWindow", "Guess", None))
        self.lineEdit_guess.setPlaceholderText(_translate("MainWindow", "Enter your guess here...", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Word to Guess", None))
        self.lbl_masked_word.setText(_translate("MainWindow", "Word to Guess", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Guesses Remaining", None))
        self.lbl_guesses_remaining.setText(_translate("MainWindow", "Guesses Remaining", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.actionLoad_custom_word_list.setText(_translate("MainWindow", "Load custom word list...", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionView_Previous_Scores.setText(_translate("MainWindow", "View Previous Scores", None))
        self.actionClear_previous_scores.setText(_translate("MainWindow", "Clear previous scores", None))

